services:
  auth-postgres:
    image: postgres:18
    container_name: auth_postgres
    environment:
      POSTGRES_DB: reservation_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql
  resource-postgres:
    image: postgres:18
    container_name: resource_postgres
    environment:
      POSTGRES_DB: reservation_resource
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - resource_postgres_data:/var/lib/postgresql

volumes:
  auth_postgres_data:
  resource_postgres_data:
