[versions]
kotlin = "1.9.25"
spring-boot = "3.4.5"
spring-dep-mgmt = "1.1.7"
spring-modulith = "1.3.5"


[libraries]
# Spring Boot Starters
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-oauth2-authorization-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server", version.ref = "spring-boot" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "spring-boot" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }

# Kotlin + JSON
jackson-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.17.1"
kotlin-reflect = "org.jetbrains.kotlin:kotlin-reflect:1.9.25"

# Modulith
spring-modulith-core = { module = "org.springframework.modulith:spring-modulith-starter-core", version.ref = "spring-modulith" }

# Test
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
kotlin-test-junit5 = "org.jetbrains.kotlin:kotlin-test-junit5:1.9.25"
spring-security-test = { module = "org.springframework.security:spring-security-test", version = "6.2.2" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dep-mgmt" }